# Package AWS Amplify Godot Engine Plugin

name: Package Plugin

on:
  push:
      tags:        
        - '*'     
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Package Plugin
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.md' ${{ github.workspace }}/addons/aws-amplify/
          mkdir -p ${{ github.workspace }}/dist/
          cp -R ${{ github.workspace }}/addons ${{ github.workspace }}/dist/
          cd ${{ github.workspace }}/dist/
          zip -r ${{ github.workspace }}/AWSAmplifyPlugin.zip .

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}

      - name: Upload Plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/AWSAmplifyPlugin.zip
          asset_name: AWSAmplifyPlugin.zip
          asset_content_type: application/zip
