# Package AWS Amplify Godot Engine Plugin

name: Package Plugin

on:
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Include Files
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.md' ${{ github.workspace }}/addons/aws-amplify/
          mkdir -p ${{ github.workspace }}/dist/
          cp -R ${{ github.workspace }}/addons/ ${{ github.workspace }}/dist/addons/
          zip -r ${{ github.workspace }}/Plugin.zip ${{ github.workspace }}/dist/

      - name: Upload Plugin Package
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: Plugin${{ github.ref_name }}
          path: |
            ${{ github.workspace }}/dist/
