# Package AWS Amplify Godot Engine Plugin

name: Package Plugin

on:
  push:
      tags:        
        - '*'     
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Package Plugin
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.md' ${{ github.workspace }}/addons/aws-amplify/
          mkdir -p ${{ github.workspace }}/dist/
          cp -R ${{ github.workspace }}/addons/ ${{ github.workspace }}/dist/addons/
          zip -r ${{ github.workspace }}/AWSAmplifyPlugin_${{ github.ref_name }}.zip ${{ github.workspace }}/dist/

      #- name: Upload Artefact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    include-hidden-files: true
      #    name: AWSAmplifyPlugin_${{ github.ref_name }}.zip
      #    path: ${{ github.workspace }}/AWSAmplifyPlugin_${{ github.ref_name }}.zip

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Plugin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/AWSAmplifyPlugin_${{ github.ref_name }}.zip
          asset_name: AWSAmplifyPlugin_${{ github.ref_name }}.zip
          asset_content_type: application/zip
